language: java
jdk:
  - oraclejdk11
deploy:
  provider: releases
  api_key:
    secure: "N1GUHlqz+cyOBU8XizIcYDC+/aj/5XpssP6uKifseJhXtBgmw8Y/cSpBlG/fHa1Do4cVmm3h3ofFb4nqAPBVZ8wbcgc/36BSAgtgZ2vEjp/u6zJ88BAXifD1rcJ5TUg6T96tshaKle4kZYdIbK2dQf0ZYb3dz1mfFlL1UZHCG7M="
  file_glob: true
  file: "build/libs/dynmap-structures-*-all.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
sudo: false
