structures:
  endcity: true
  fortress: true
  igloo: true
  mansion: true
  mineshaft: false
  monument: true
  stronghold: true
  temple: true
  witch: true
  village: true
#labels:
#  endcity: "End City"
#  fortress: "Nether Fortress"
#  igloo: "Igloo"
#  mansion: "Woodland Mansion"
#  mineshaft: "Abandoned Mineshaft"
#  monument: "Ocean Monument"
#  stronghold: "Stronghold"
#  temple: "Temple"
#  witch: "Witch Hut"
#  village: "Village"
layer:
  name: "Structures"
  hidebydefault: false
  layerprio: 10
  nolabels: false
  minzoom: 0
  inc-coord: false
