structures:
  deserttemple: true
  endcity: true
  fortress: true
  igloo: true
  jungletemple: true
  mansion: true
  mineshaft: false
  monument: true
  stronghold: true
  witch: true
  village: true
layer:
  name: "Structures"
  hidebydefault: false
  layerprio: 10
  nolabels: false
  minzoom: 0
  inc-coord: false
