structures:
  buriedtreasure: true
  desertpyramid: true
  endcity: true
  fortress: true
  igloo: true
  junglepyramid: true
  mansion: true
  mineshaft: false
  monument: true
  oceanruins: true
  shipwreck: true
  stronghold: true
  swamphut: true
  village: true
events:
  chunk-generate:
    enabled: false
  chunk-load:
    enabled: false
  player-move:
    enabled: true
    radius: 1
layer:
  name: "Structures"
  hidebydefault: false
  layerprio: 10
  nolabels: false
  minzoom: 0
  inc-coord: false
